# Generated by Django 5.1.7 on 2025-04-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_is_read_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_review', 'New Review'), ('new_thread', 'New Thread'), ('new_thread_reply', 'New Reply'), ('join_request', 'New Join Request'), ('join_response', 'New Join Response'), ('claim_request', 'New Claim Request'), ('claim_response', 'New Claim Response'), ('general_request', 'New Request'), ('general_response', 'New Response')], max_length=20),
        ),
    ]
