# Generated by Django 5.1.7 on 2025-03-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_remove_request_employee_remove_request_employer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestreply',
            options={'verbose_name': 'Request Reply', 'verbose_name_plural': 'Request Replies'},
        ),
    ]
