# Generated by Django 5.1.7 on 2025-04-02 08:14

import django.core.validators
import secure_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securefile',
            name='file',
            field=models.FileField(upload_to=secure_files.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'png', 'jpeg', 'webp', 'xlsx']), secure_files.models.validate_file_size]),
        ),
    ]
