# Generated by Django 5.1.7 on 2025-03-29 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_claimed_by_remove_company_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Name must only contain letters, spaces, and hyphens (max 100 characters).', regex='^[a-zA-Z\\s-]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Name must only contain letters, spaces, and hyphens (max 100 characters).', regex='^[a-zA-Z\\s-]{1,100}$')]),
        ),
    ]
