# Generated by Django 5.1.7 on 2025-04-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='profile_pic',
        ),
    ]
