# Generated by Django 5.1.7 on 2025-04-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_remove_thread_created_by_thread_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='type',
            field=models.CharField(choices=[('forum', 'Forum'), ('announcement', 'Announcement')], default='forum', max_length=20),
        ),
        migrations.AlterField(
            model_name='thread',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Internal'), ('private', 'Private')], default='internal', max_length=10),
        ),
    ]
