# Generated by Django 5.1.7 on 2025-04-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_mention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='mentioned_by',
        ),
    ]
