# Generated by Django 5.1.7 on 2025-03-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_deleted_at_review_is_deleted_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewreply',
            options={'verbose_name': 'Review Reply', 'verbose_name_plural': 'Review Replies'},
        ),
    ]
