# Generated by Django 5.1.7 on 2025-04-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviewreply_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Required if no user is associated and not anonymous', max_length=100, null=True),
        ),
    ]
