# Generated by Django 5.1.7 on 2025-04-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfa_enabled',
        ),
    ]
