name: OWASP ZAP Baseline Scan

on:
  workflow_run:
    workflows: ["DevSecOps CD Pipeline"]
    types:
      - completed

jobs:
  zap_scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: ZAP Scan
    permissions:
      contents: read
      actions: read  # necessary to access previous workflow artifacts
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for app to be ready
        run: sleep 30

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://feedit.online'
          fail_action: false
          artifact_name: zap-report
          cmd_options: '-w report_md.md -r zap_report.html'
          allow_issue_writing: false
        continue-on-error: true

      - name: Display ZAP Summary in GitHub UI
        run: |
          if [ -f report_md.md ]; then
            echo "## 🔐 OWASP ZAP Baseline Scan Summary" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat report_md.md >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ No Markdown report found. ZAP may have failed or produced no output." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload ZAP Report Files
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_md.md
            zap_report.html
